"""Generate docs/tts-systems.md from data/research/findings.json.

The findings JSON is the structured output of the multi-agent research workflow
(7 TTS systems + Qwen3-ASR). This script renders it into a human-readable reference
so the exact phonetic-control syntax and run notes for each model live in the repo.
Re-run after refreshing the research.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "data" / "research" / "findings.json"
OUT = ROOT / "docs" / "tts-systems.md"


def yn(b: bool) -> str:
    return "✅" if b else "❌"


def main() -> None:
    data = json.loads(SRC.read_text(encoding="utf-8"))
    findings = data["findings"]
    asr = data["asr"]
    lines: list[str] = []
    w = lines.append

    w("# TTS systems — capability reference\n")
    w("> Auto-generated by `scripts/gen_systems_doc.py` from `data/research/findings.json` "
      "(multi-agent research). Verify against upstream before relying on exact syntax.\n")

    # ---- summary matrix ----
    w("## Phonetic-control & accent matrix\n")
    w("| Model | Pinyin | Zhuyin | Phoneme/IPA | zh-TW native | Code-switch | Voice mode | Needs ref audio | Runnable |")
    w("|---|---|---|---|---|---|---|---|---|")
    for f in findings:
        pc, vm = f["phonetic_control"], f["voice_mode"]
        mid = f["model_id"].split("(")[0].strip()
        tw = "✅ native" if "strong" in f["zh_tw_support"].lower()[:40] or "core design" in f["zh_tw_support"].lower() else "❌ mainland"
        w(f"| `{mid}` | {yn(pc['supports_pinyin'])} | {yn(pc['supports_zhuyin'])} | "
          f"{yn(pc['supports_phoneme_or_ipa'])} | {tw} | {f['code_switch'][:3] and '✅'} | "
          f"{vm['type']} | {yn(vm['needs_reference_audio'])} | {f['runnable_verdict']} |")
    w("")

    # ---- per-model detail ----
    w("## Per-model detail\n")
    for f in findings:
        pc, vm, hr = f["phonetic_control"], f["voice_mode"], f["how_to_run"]
        w(f"### {f['model_id']}\n")
        w(f"- **Repo:** {f.get('github_repo','') or '(none)'}")
        w(f"- **License:** {f['license']}")
        w(f"- **Runnable:** {f['runnable_verdict']} (confidence: {f['confidence']})")
        w(f"- **GPU / disk / sample rate:** {hr['gpu_vram_gb']} / {hr['disk_gb']} / {hr['sample_rate_hz']} Hz"
          f" / trust_remote_code={hr['trust_remote_code']}")
        w(f"\n**What it is.** {f['summary']}\n")
        w(f"**Phonetic control** (pinyin={yn(pc['supports_pinyin'])} zhuyin={yn(pc['supports_zhuyin'])} "
          f"phoneme/ipa={yn(pc['supports_phoneme_or_ipa'])}, confidence={pc['confidence']}):\n")
        w(f"{pc['mechanism']}\n")
        if pc.get("example_input"):
            w(f"- _Example:_ `{pc['example_input']}`\n")
        w(f"**zh-TW support.** {f['zh_tw_support']}\n")
        w(f"**Code-switch.** {f['code_switch']}\n")
        w(f"**Voice mode.** type={vm['type']}, needs_reference_audio={vm['needs_reference_audio']}, "
          f"needs_reference_text={vm['needs_reference_text']}.\n\n{vm['notes']}\n")
        w(f"**Install.** \n```\n{hr['install']}\n```\n")
        w(f"**Minimal inference.**\n```python\n{hr['entrypoint_snippet']}\n```\n")
        w(f"**Modal notes.** {f['modal_notes']}\n")
        if f.get("citations"):
            w("**Sources.** " + " · ".join(f["citations"][:8]) + "\n")
        w("---\n")

    # ---- ASR ----
    w("## Evaluation ASR — Qwen/Qwen3-ASR-1.7B\n")
    hr = asr["how_to_run"]
    w(f"- **GPU / trust_remote_code:** {hr['gpu_vram_gb']} / {hr['trust_remote_code']}")
    w(f"- **Input audio:** {hr['input_audio']}\n")
    w(f"{asr['summary']}\n")
    w(f"**Install.**\n```\n{hr['install']}\n```\n")
    w(f"**Minimal inference.**\n```python\n{hr['entrypoint_snippet']}\n```\n")
    w(f"**Context biasing.** {asr['context_biasing']}\n")
    w(f"**Scoring recipe.** {asr['scoring_recipe']}\n")
    w(f"**Modal notes.** {asr['modal_notes']}\n")
    if asr.get("citations"):
        w("**Sources.** " + " · ".join(asr["citations"][:8]) + "\n")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes, {len(findings)} models)")


if __name__ == "__main__":
    main()
